#' @title Genomic Quality Assessment Pipeline: CheckM
#' @description This script analyzes genome quality metrics (Completeness, 
#' Contamination, Heterogeneity) generated by CheckM. It produces 
#' publication-ready figures and conditional formatted Excel reports 
#' following MIMAG standards.
#' 
#' @details 
#' Input files (CheckM tabular and Metadata) must be in the script's root directory.
#' Outputs are saved to './outputs'.
#'
#' @author [Seu Nome] (ORCID: 0000-XXXX-XXXX-XXXX)
#' @date 2026-02-17
#' @version 1.1.1 (Fixed Plot Limits)
#' @license MIT License
#' @doi 10.5281/zenodo.XXXXX (Placeholder)
#'
#' @dependencies
#' - R version 4.5.2
#' - Bioconductor version 3.22
#' - Core Packages: tidyverse, ggplot2, patchwork, openxlsx, viridis, scales

# ==============================================================================
# 1. SETUP AND LIBRARIES
# ==============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(ggplot2)
  library(ggpubr)
  library(patchwork)
  library(openxlsx)
  library(viridis)
  library(scales)
})

# ==============================================================================
# 2. HELPER FUNCTIONS
# ==============================================================================

#' Load and Process CheckM Data
#' @description Reads CheckM tabular output and merges with metadata.
#' @param file_checkm Path to the CheckM .tabular file.
#' @param file_meta Path to the Metadata .tsv file.
#' @param sample_order Vector of strings defining the plot order.
#' @return A tibble with processed and ordered data.
load_checkm_data <- function(file_checkm, file_meta, sample_order) {
  
  # Validation
  if (!file.exists(file_checkm)) stop("CheckM file not found at: ", file_checkm)
  if (!file.exists(file_meta)) stop("Metadata file not found at: ", file_meta)
  
  # Read
  meta_df <- readr::read_tsv(file_meta, show_col_types = FALSE)
  checkm_df <- readr::read_tsv(file_checkm, show_col_types = FALSE)
  
  # Process
  processed <- checkm_df %>%
    dplyr::rename(Sample = `Bin Id`) %>%
    dplyr::left_join(meta_df, by = c("Sample" = "CheckM")) %>%
    dplyr::mutate(Strain = dplyr::coalesce(Nome_Real, Sample)) %>% 
    dplyr::rename(
      Lineage = `Marker lineage`,
      N_Genomes = `# genomes`,
      N_Markers = `# markers`,
      N_Marker_Sets = `# marker sets`,
      Strain_Heterogeneity = `Strain heterogeneity`
    ) %>%
    dplyr::select(Strain, Lineage, N_Genomes, N_Markers, N_Marker_Sets, 
                  Completeness, Contamination, Strain_Heterogeneity) %>%
    dplyr::mutate(Strain = factor(Strain, levels = sample_order)) %>%
    dplyr::filter(!is.na(Strain))
  
  return(processed)
}

#' Save Conditional Formatted Excel Report
#' @description Creates an XLSX file with green highlighting for high-quality genomes.
#' @param data Processed tibble.
#' @param output_path Destination path.
save_quality_report <- function(data, output_path) {
  
  wb <- openxlsx::createWorkbook()
  sheet_name <- "CheckM Quality Assessment"
  openxlsx::addWorksheet(wb, sheet_name)
  openxlsx::writeData(wb, sheet_name, data, startRow = 1)
  
  # Styles
  header_style <- openxlsx::createStyle(
    fontColour = "#FFFFFF", fgFill = "#4F81BD", halign = "center", 
    valign = "center", textDecoration = "bold", border = "TopBottomLeftRight"
  )
  data_style <- openxlsx::createStyle(halign = "center", valign = "center", border = "TopBottomLeftRight")
  good_quality_style <- openxlsx::createStyle(fgFill = "#C6EFCE", fontColour = "#006100")
  
  # Apply basic styles
  openxlsx::addStyle(wb, sheet_name, header_style, rows = 1, cols = 1:ncol(data), gridExpand = TRUE)
  openxlsx::addStyle(wb, sheet_name, data_style, rows = 2:(nrow(data) + 1), cols = 1:ncol(data), gridExpand = TRUE)
  
  # Apply Conditional Formatting (MIMAG Standards: Comp >= 95, Cont <= 5)
  # Assuming Completeness is col 6 and Contamination is col 7
  openxlsx::conditionalFormatting(wb, sheet_name, cols = 6, rows = 2:(nrow(data)+1), 
                                  rule = ">=95", style = good_quality_style)
  openxlsx::conditionalFormatting(wb, sheet_name, cols = 7, rows = 2:(nrow(data)+1), 
                                  rule = "<=5", style = good_quality_style)
  
  openxlsx::setColWidths(wb, sheet_name, cols = 1:ncol(data), widths = "auto")
  openxlsx::saveWorkbook(wb, output_path, overwrite = TRUE)
}

#' Generate Scientific Theme
theme_nature <- function() {
  theme_minimal(base_family = "sans", base_size = 11) +
    theme(
      plot.title = element_text(face = "bold", hjust = 0.5, size = 12),
      axis.text.x = element_text(angle = 45, hjust = 1, color = "black"),
      axis.text.y = element_text(color = "black"),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
      legend.position = "bottom"
    )
}

# ==============================================================================
# 3. MAIN EXECUTION BLOCK
# ==============================================================================

# Configuration: Files must be in the root directory
CONFIG <- list(
  FILE_CHECKM = "Galaxy36-[CheckM lineage_wf on dataset 1-10_ Bin statistics].tabular",
  FILE_META   = "Metadados.tsv",
  DIR_OUT     = "outputs"
)

# Sample Order for biological consistency
SAMPLE_ORDER <- c(
  "K-12 MG1655 (negative control)", "O157:H7 Sakai (reference)", "O157:H7 EDL933",
  "O145:H28 RM12581", "O121:H19 FWSEC0006", "O111:H8 7-58 72A",
  "O104:H4 2011C 3493", "O103:H2 12009", "O45:H2 FWSEC0003", "O26:H11 11368"
)

main <- function() {
  
  # 1. Environment Setup
  current_wd <- getwd()
  cat("\n[INFO] Environment: R v4.5.2 / Bioconductor v3.22\n")
  cat("[INFO] Working Directory:", current_wd, "\n")
  
  dir_output <- file.path(current_wd, CONFIG$DIR_OUT)
  if (!dir.exists(dir_output)) {
    dir.create(dir_output, recursive = TRUE)
    cat("[INFO] Output directory created:", dir_output, "\n")
  }
  
  # 2. Load Data
  cat("[1/4] Loading and Processing Data...\n")
  path_checkm <- file.path(current_wd, CONFIG$FILE_CHECKM)
  path_meta   <- file.path(current_wd, CONFIG$FILE_META)
  
  checkm_processed <- load_checkm_data(path_checkm, path_meta, SAMPLE_ORDER)
  
  # 3. Export Report
  cat("[2/4] Generating Excel Report...\n")
  save_quality_report(checkm_processed, file.path(dir_output, "Table_CheckM_Quality_Assessment.xlsx"))
  
  # 4. Visualization
  cat("[3/4] Generating Plots...\n")
  colors_strains <- viridis::viridis(length(SAMPLE_ORDER), option = "D", begin = 0.1, end = 0.9)
  
  # Plot 1: Completeness
  p1 <- ggplot(checkm_processed, aes(x = Strain, y = Completeness, fill = Strain)) +
    geom_col(color = "black", width = 0.7) +
    geom_hline(yintercept = 95, linetype = "dashed", color = "red") +
    annotate("text", x = 0.5, y = 96, label = ">95% Threshold", 
             hjust = 0, vjust = 0, size = 3, color = "red") +
    scale_fill_manual(values = colors_strains) +
    scale_y_continuous(limits = c(0, 105), expand = c(0, 0)) +
    labs(title = "Genome Completeness", y = "Completeness (%)", x = NULL) +
    theme_nature() + theme(legend.position = "none", axis.text.x = element_blank())
  
  # Plot 2: Contamination
  p2 <- ggplot(checkm_processed, aes(x = Strain, y = Contamination, fill = Strain)) +
    geom_col(color = "black", width = 0.7) +
    geom_hline(yintercept = 5, linetype = "dashed", color = "red") +
    annotate("text", x = 0.5, y = 5.5, label = "<5% Threshold", 
             hjust = 0, vjust = 0, size = 3, color = "red") +
    scale_fill_manual(values = colors_strains) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
    labs(title = "Genome Contamination", y = "Contamination (%)", x = NULL) +
    theme_nature() + theme(legend.position = "none", axis.text.x = element_blank())
  
  # Plot 3: Scatter Bi-plot (CORREÇÃO AQUI)
  # Removido limits fixos para evitar cortar a linha de threshold ou dados
  p3 <- ggplot(checkm_processed, aes(x = Completeness, y = Contamination, color = Strain)) +
    annotate("rect", xmin = 95, xmax = 100, ymin = 0, ymax = 5, 
             alpha = 0.1, fill = "green") +
    geom_point(size = 5, alpha = 0.8) +
    geom_vline(xintercept = 95, linetype = "dashed", color = "red") +
    geom_hline(yintercept = 5, linetype = "dashed", color = "red") +
    scale_color_manual(values = colors_strains) +
    # FIX: Limits removed to prevent "Removed 1 row" warning if threshold (95) is outside view
    labs(title = "Quality Assessment (Bi-plot)", 
         subtitle = "Green zone indicates high-quality genomes (MIMAG)",
         x = "Completeness (%)", y = "Contamination (%)") +
    theme_nature() + theme(legend.position = "right")
  
  # Plot 4: Heatmap
  heatmap_data <- checkm_processed %>%
    dplyr::select(Strain, Completeness, Contamination, Strain_Heterogeneity) %>%
    tidyr::pivot_longer(-Strain, names_to = "Metric", values_to = "Value")
  
  p4 <- ggplot(heatmap_data, aes(x = Metric, y = Strain, fill = Value)) +
    geom_tile(color = "white") +
    geom_text(aes(label = round(Value, 2)), color = "white", fontface = "bold", size = 3) +
    scale_fill_viridis(option = "C", direction = -1) +
    labs(title = "Quality Metrics Heatmap", x = NULL, y = NULL) +
    theme_nature() + 
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5))
  
  # Combine
  layout_final <- ((p1 / p2) | p3) + plot_annotation(tag_levels = 'A')
  
  # Save
  cat("[4/4] Saving Figures and Statistics...\n")
  ggsave(file.path(dir_output, "Figure_CheckM_Combined.png"), 
         layout_final, width = 14, height = 8, dpi = 600, bg = "white")
  
  # Descriptive Stats
  stats <- checkm_processed %>%
    dplyr::summarise(
      Mean_Comp = mean(Completeness), SD_Comp = sd(Completeness),
      Mean_Cont = mean(Contamination), SD_Cont = sd(Contamination)
    )
  readr::write_csv(stats, file.path(dir_output, "CheckM_Descriptive_Stats.csv"))
  
  # Save Session Info
  writeLines(c(
    paste("Pipeline Run Date:", Sys.time()),
    paste("R Version:", R.version.string),
    "Bioconductor: v3.22 (Expected)",
    capture.output(sessionInfo())
  ), file.path(dir_output, "session_info_CheckM.txt"))
  
  cat("\n✓ PIPELINE COMPLETED SUCCESSFULLY.\n")
  cat("✓ Results saved in:", dir_output, "\n")
}

# Execute Main
if (!interactive()) {
  main()
} else {
  cat("Script loaded. Ensure CheckM file and Metadata are in root directory and run 'main()'.\n")
}